import { c as createComponent, r as renderTemplate, m as maybeRenderHead, u as unescapeHTML } from './astro/server_DhV-obnq.mjs';
import 'kleur/colors';
import 'clsx';

const html = "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam in venenatis enim, et ultricies tortor. Praesent sit amet accumsan ligula.</p>\n<h2 id=\"titre-h2\">Titre H2</h2>\n<p>Etiam et nunc nec ligula ullamcorper dapibus. Nullam ut malesuada magna, vel scelerisque ligula.</p>\n<h3 id=\"titre-h3\">Titre H3</h3>\n<p>Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Duis vehicula lacus in metus convallis, non pharetra tortor gravida.</p>\n<h4 id=\"titre-h4\">Titre H4</h4>\n<p>Cras venenatis nisl in nisl pretium, in auctor mi sagittis.</p>\n<h5 id=\"titre-h5\">Titre H5</h5>\n<p>Nam pharetra nulla ac lacus suscipit, ac tincidunt felis fermentum.</p>\n<h6 id=\"titre-h6\">Titre H6</h6>\n<p>Aliquam erat volutpat. Sed posuere dapibus massa, sed fringilla risus ullamcorper et.</p>\n<hr>\n<h2 id=\"paragraphe\">Paragraphe</h2>\n<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</p>\n<h2 id=\"liste-non-ordonnée\">Liste Non Ordonnée</h2>\n<ul>\n<li>Item 1</li>\n<li>Item 2\n<ul>\n<li>Sous-item 1</li>\n<li>Sous-item 2</li>\n</ul>\n</li>\n<li>Item 3</li>\n</ul>\n<h2 id=\"liste-ordonnée\">Liste Ordonnée</h2>\n<ol>\n<li>Première tâche</li>\n<li>Deuxième tâche\n<ol>\n<li>Sous-tâche 1</li>\n<li>Sous-tâche 2</li>\n</ol>\n</li>\n<li>Troisième tâche</li>\n</ol>\n<h2 id=\"lien\">Lien</h2>\n<p>Voici un <a href=\"https://www.openai.com\">lien vers OpenAI</a>.</p>\n<h2 id=\"image\">Image</h2>\n<p><img src=\"https://via.placeholder.com/150\" alt=\"Image de Test\" title=\"Image Placeholder\"></p>\n<h2 id=\"code\">Code</h2>\n<p>Voici un exemple de code en JavaScript :</p>\n<pre class=\"astro-code github-dark\" style=\"background-color:#24292e;color:#e1e4e8; overflow-x: auto;\" tabindex=\"0\" data-language=\"js\"><code><span class=\"line\"><span style=\"color:#F97583\">function</span><span style=\"color:#B392F0\"> sayHello</span><span style=\"color:#E1E4E8\">() {</span></span>\n<span class=\"line\"><span style=\"color:#E1E4E8\">  console.</span><span style=\"color:#B392F0\">log</span><span style=\"color:#E1E4E8\">(</span><span style=\"color:#9ECBFF\">\"Hello, world!\"</span><span style=\"color:#E1E4E8\">);</span></span>\n<span class=\"line\"><span style=\"color:#E1E4E8\">}</span></span>\n<span class=\"line\"></span></code></pre>";

				const frontmatter = {"title":"Titre Article 3 Custom OK","description":"Description custom OK","tags":"Catégorie 1","image":"post-1.webp","date":"2025-08-24T00:00:00.000Z","author":"author-1","relatedPosts":["post-1"]};
				const file = "C:/Users/Utilisateur/zatchou74/src/content/posts/post3.md";
				const url = undefined;
				function rawContent() {
					return "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam in venenatis enim, et ultricies tortor. Praesent sit amet accumsan ligula.\r\n\r\n## Titre H2\r\n\r\nEtiam et nunc nec ligula ullamcorper dapibus. Nullam ut malesuada magna, vel scelerisque ligula.\r\n\r\n### Titre H3\r\n\r\nVestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Duis vehicula lacus in metus convallis, non pharetra tortor gravida.\r\n\r\n#### Titre H4\r\n\r\nCras venenatis nisl in nisl pretium, in auctor mi sagittis.\r\n\r\n##### Titre H5\r\n\r\nNam pharetra nulla ac lacus suscipit, ac tincidunt felis fermentum.\r\n\r\n###### Titre H6\r\n\r\nAliquam erat volutpat. Sed posuere dapibus massa, sed fringilla risus ullamcorper et.\r\n\r\n---\r\n\r\n## Paragraphe\r\n\r\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.\r\n\r\n## Liste Non Ordonnée\r\n\r\n- Item 1\r\n- Item 2\r\n  - Sous-item 1\r\n  - Sous-item 2\r\n- Item 3\r\n\r\n## Liste Ordonnée\r\n\r\n1. Première tâche\r\n2. Deuxième tâche\r\n   1. Sous-tâche 1\r\n   2. Sous-tâche 2\r\n3. Troisième tâche\r\n\r\n## Lien\r\n\r\nVoici un [lien vers OpenAI](https://www.openai.com).\r\n\r\n## Image\r\n\r\n![Image de Test](https://via.placeholder.com/150 \"Image Placeholder\")\r\n\r\n## Code\r\n\r\nVoici un exemple de code en JavaScript :\r\n\r\n```js\r\nfunction sayHello() {\r\n  console.log(\"Hello, world!\");\r\n}\r\n";
				}
				function compiledContent() {
					return html;
				}
				function getHeadings() {
					return [{"depth":2,"slug":"titre-h2","text":"Titre H2"},{"depth":3,"slug":"titre-h3","text":"Titre H3"},{"depth":4,"slug":"titre-h4","text":"Titre H4"},{"depth":5,"slug":"titre-h5","text":"Titre H5"},{"depth":6,"slug":"titre-h6","text":"Titre H6"},{"depth":2,"slug":"paragraphe","text":"Paragraphe"},{"depth":2,"slug":"liste-non-ordonnée","text":"Liste Non Ordonnée"},{"depth":2,"slug":"liste-ordonnée","text":"Liste Ordonnée"},{"depth":2,"slug":"lien","text":"Lien"},{"depth":2,"slug":"image","text":"Image"},{"depth":2,"slug":"code","text":"Code"}];
				}

				const Content = createComponent((result, _props, slots) => {
					const { layout, ...content } = frontmatter;
					content.file = file;
					content.url = url;

					return renderTemplate`${maybeRenderHead()}${unescapeHTML(html)}`;
				});

export { Content, compiledContent, Content as default, file, frontmatter, getHeadings, rawContent, url };
